apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-sample

resources:
- ../../base

patchesStrategicMerge:
- ingress-patch.yaml

replicas:
- name: nginx
  count: 3

commonLabels:
  environment: prod

images:
- name: nginx
  newTag: 1.25-alpine 