apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-prod-ingress
  labels:
    name: nginx
spec:
  rules:
  - host: "prod.localhost"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-nginx
            port: 
              number: 80
