apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-system
  labels:
    app: redis
data:
  redis.conf: |
    # Redis 기본 설정
    bind 0.0.0.0
    port 6379
    protected-mode yes
    
    # 메모리 설정
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # 로깅
    loglevel notice
    
    # 스냅샷 설정
    save 900 1
    save 300 10
    save 60 10000
    
    # AOF 설정
    appendonly yes
    appendfsync everysec
    
    # 보안
    requirepass redis-password 