apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - statefulset.yaml
  - service.yaml

commonLabels:
  app: redis
  version: v7.2.0 