apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-system
data:
  redis.conf: |
    # Redis Production 환경 설정
    bind 0.0.0.0
    port 6379
    protected-mode yes
    
    # 메모리 설정 (Production - 높은 성능)
    maxmemory 1gb
    maxmemory-policy allkeys-lru
    
    # 로깅
    loglevel notice
    logfile /data/redis.log
    
    # 스냅샷 설정 (Production - 안정적인 백업)
    save 900 1
    save 300 10
    save 60 10000
    
    # AOF 설정 (Production - 강력한 내구성)
    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    
    # 보안
    requirepass prod-redis-secure-password
    
    # 성능 최적화
    tcp-keepalive 300
    timeout 0
    
    # 슬로우 로그
    slowlog-log-slower-than 10000
    slowlog-max-len 128 