apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-system
data:
  postgresql.conf: |
    # PostgreSQL Production 환경 설정
    listen_addresses = '*'
    port = 5432
    
    # 메모리 설정 (Production - 고성능)
    shared_buffers = 512MB
    effective_cache_size = 2GB
    work_mem = 8MB
    maintenance_work_mem = 256MB
    
    # 연결 설정
    max_connections = 200
    
    # 로깅 설정 (운영 최적화)
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_statement = 'ddl'
    log_min_duration_statement = 5000
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d '
    log_rotation_age = 1d
    log_rotation_size = 100MB
    
    # WAL 설정 (안정성 최우선)
    wal_level = replica
    max_wal_size = 2GB
    min_wal_size = 256MB
    wal_compression = on
    
    # 체크포인트 설정
    checkpoint_completion_target = 0.9
    checkpoint_timeout = 15min
    
    # 성능 최적화
    random_page_cost = 1.1
    effective_io_concurrency = 200
    
    # 백그라운드 작업자
    max_worker_processes = 8
    max_parallel_workers_per_gather = 4
    max_parallel_workers = 8
    
    # 자동 vacuum 설정
    autovacuum = on
    autovacuum_max_workers = 3
    autovacuum_naptime = 20s
    
    # 통계 수집
    track_activities = on
    track_counts = on
    track_io_timing = on
    track_functions = all 