apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gitops-prod
  annotations:
    config.kubernetes.io/local-config: "true"

# 모든 프로젝트의 prod overlay를 포함
resources:
  - ../../projects/nginx/overlay/prod
  - ../../projects/postgres/overlay/prod
  - ../../projects/redis/overlay/prod

# 공통 라벨 추가
commonLabels:
  environment: prod
  managed-by: kustomize
  gitops-project: "true"

# 공통 어노테이션 추가
commonAnnotations:
  deployed-by: gitops
  environment: prod 