apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-system
data:
  redis.conf: |
    # Redis Stage 환경 설정
    bind 0.0.0.0
    port 6379
    protected-mode yes
    
    # 메모리 설정 (Stage - 낮은 리소스)
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    
    # 로깅
    loglevel notice
    
    # 스냅샷 설정 (Stage - 빈번한 스냅샷)
    save 300 10
    save 60 1000
    
    # AOF 설정
    appendonly yes
    appendfsync everysec
    
    # 보안
    requirepass stage-redis-password
    
    # 개발용 설정
    timeout 300 