apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-system

resources:
- ../../base

patchesStrategicMerge:
- configmap-patch.yaml
- statefulset-patch.yaml

commonLabels:
  environment: stage

images:
- name: redis
  newTag: 7.2-alpine 