apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-system
  labels:
    app: postgres
data:
  postgresql.conf: |
    # PostgreSQL 기본 설정
    listen_addresses = '*'
    port = 5432
    
    # 메모리 설정
    shared_buffers = 128MB
    effective_cache_size = 512MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    
    # 연결 설정
    max_connections = 100
    
    # 로깅 설정
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_statement = 'all'
    log_min_duration_statement = 1000
    
    # WAL 설정
    wal_level = replica
    max_wal_size = 1GB
    min_wal_size = 80MB
    
    # 체크포인트 설정
    checkpoint_completion_target = 0.9
    
  pg_hba.conf: |
    # PostgreSQL 접근 제어
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            md5
    host    all             all             ::1/128                 md5
    host    all             all             0.0.0.0/0               md5

  init-db.sql: |
    -- 애플리케이션용 데이터베이스 및 사용자 생성
    CREATE DATABASE myapp;
    CREATE USER myapp WITH ENCRYPTED PASSWORD 'myapp-password';
    GRANT ALL PRIVILEGES ON DATABASE myapp TO myapp;
    
    -- 확장 설치
    \c myapp;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"; 