apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres-system
  labels:
    app: postgres
type: Opaque
data:
  # postgres (base64 encoded)
  postgres-username: cG9zdGdyZXM=
  # postgres-password (base64 encoded)  
  postgres-password: cG9zdGdyZXMtcGFzc3dvcmQ=
  # myapp (base64 encoded)
  app-username: bXlhcHA=
  # myapp-password (base64 encoded)
  app-password: bXlhcHAtcGFzc3dvcmQ= 