apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-system

resources:
- ../../base

patchesStrategicMerge:
- configmap-patch.yaml
- statefulset-patch.yaml

commonLabels:
  environment: stage

images:
- name: postgres
  newTag: 16-alpine 